# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leiming Yu 
email: ylm@ece.neu.edu 
description: Blogs for research, study and fun. 
baseurl: ""
url: "https://3upperm2n.github.io/"
twitter_username: yu_leiming 
github_username:  3upperm2n 
paginate: 10 

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
